### ISSUE TITLE
Flash Dev Who Would Love to Offer Support!

### ISSUE THREAD

**Issue by Cleod9** [JasonHuang3D/AJC-Flash-WebAssembly-Examples#2]
Hey, just stumbled upon your repo and I think this effort is pretty impressive! I'd love to help any way I can, although I'm not sure how much I can help in terms of lower-leveled programming (though I'm willing to learn a bit!)

What I can offer you that I think might be useful is a pretty advanced test-case, since I'm the creator behind what is probably one of the largest Flash games on the net, Super Smash Flash 2:

https://www.mcleodgaming.com/games/ssf2/

This is a massive fan game split across several hundred individual SWFs (700MB  total and counting), and makes extensive use of the most common game-related functions in the Flash API: bitmap data, networking, filters/effects, nested animations, gamepad support, external SWFs, you name it.

I use FlashDevelop as my main IDE so I'd love to be able to help test things out with my workflow in hopes to getting this project to the point where it could execute such a massive project as mine.

I'll certainly be following along with this project, let me know if there's anything I can do to help!

**Comment by ROBERT-MCDOWELL** [comment]
despite of my very low C++ knowledge I would like to contribute actively like promote, as3 development servers etc... about flash games, maybe the guys from habbohotel (www.habbo.com) will help as they currently have more than 130 millions players

**Comment by JasonHuang3D** [comment]
Thx guys. After 2 months hard working we successfully implement full gpu-based vector graphics and text. I might upgrade this repo this month, to bring you guys more exciting things. Catch me up on emails. You may find my email address in my profile.
