### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [JasonHuang3D/AJC-Flash-WebAssembly-Examples#3]
Maybe:
- Rename your repo with a more simple anf efficient name like "Flash2Wasm" will help developers to find your repo
- any way to convert SWF directly to WASM would be fantastic (Big As2 project will be saved and returns will be very powerful for you)
- create an app that convert automatically any SWF to WASM is the key of a lot of good return for you and time gain for all developers.
Thanks

**Comment by JasonHuang3D** [comment]
Thx for your suggestions. Parsing  swf would be possible if we can finish the cpp code base just on time:)
