### ISSUE TITLE
Create track for Flash API status implementation

### ISSUE THREAD

**Issue by blackjyn** [JasonHuang3D/AJC-Flash-WebAssembly-Examples#4]
First I would like to thank you so much guys for your hard work
I have tried some simple code that involved Flash's graphics (like graphics.beginfill etc) and unfortunately 
it returns 

>Access of possibly undefined property graphics **graphics.endFill();**

I know the Flash API implementation is incomplete , but dedicated page to track the implementation status would be very nice
Thank you

**Comment by Cleod9** [comment]
This would be useful! Something like the feature matrix from OpenFL would be nice:

http://www.openfl.org/learn/docs/feature-matrix/

**Comment by blackjyn** [comment]
@Cleod9 naah.. something like that is what we need

**Comment by JasonHuang3D** [comment]
Gpu based vector graphics and text are ready. I may make a push this month

**Comment by blackjyn** [comment]
It is almost 1 month but still no updates :cry:
