### ISSUE TITLE
Does it support SWFs?

### ISSUE THREAD

**Issue by demurgos** [JasonHuang3D/AJC-Flash-WebAssembly-Examples#5]
Hi,
I have a question regarding your project.

I have my own project called [`OpenFlash`](https://github.com/open-flash). My goal is to continue the work of Gnash and Shumway by creating a drop-in replacement for the Flash Player Plugin. I have an SWF parser, AST, and web-based renderer (using canvas). I am able to play simple shapes and sprites and started to work on the AVM. My library is implemented both in Typescript and Rust: I managed to get an experimental version compiled to Wasm.

I'd like to understand if your project also aims at running existing SWF files or if it is for new projects? Instead of compiling to SWF, they'd compile for your target.

**Comment by JasonHuang3D** [comment]
Good idea, parsing swf will be next step. Currently we are focusing on implementing flash APIs .

**Comment by demurgos** [comment]
Ok, thanks for the answer: I understand that this project currently requires a new build step for old SWF files.
